# Generated by Django 4.1.7 on 2023-03-17 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_users_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='users_followed',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
